### ISSUE TITLE
Snapshot 2.0 - Complex.valueOf(1.3038404810405297).asin() imaginary part should be negative

### ISSUE THREAD

**Issue by axkr** [Hipparchus-Math/hipparchus#128]
IMO the  imaginary part should be negative here?

```
public class ComplexASin {

  public static void main(String[] args) {
    // gives wrong (1.5707963267948966, 0.7610396837318267)
    System.out.println(Complex.valueOf(1.3038404810405297).asin());
  }
}
```

**Comment by maisonobe** [comment]
The point is exactly on a branch cut so it would in fact depend on the sign of 0 in z = 1.3038404810405297 + 0i.
The can be seen in the plot at Mathworld: https://mathworld.wolfram.com/InverseSine.html,
and is confirmed by using Wolfram alpha, with tiny non-zero values for the imaginary part:
https://www.wolframalpha.com/input/?i=asin%281.3038404810405297%2B1.0e-9i%29 gives a positive imaginary part,
but https://www.wolframalpha.com/input/?i=asin%281.3038404810405297-1.0e-9i%29 gives a negative imaginary part.

When we build a Complex setting only the real part, the zero we put is a positive zero.
You could perhaps try to use `new Complex(1.3038404810405297, -0.0)` to see if it changes something.

**Comment by axkr** [comment]
Yes that might be, but before 2.0 it got the negative sign. So something must probably be changed:
- http://matheclipse.org/input?i=arcsin(1.3038404810405297)

**Comment by maisonobe** [comment]
This is most probably this change:
https://github.com/Hipparchus-Math/hipparchus/commit/8ea1a6d411#diff-78d293cfb78fcd885a7158e1df66569baf65b585b1677246fdca09b95d03b9faL1277

The `sqrt1z` is called by both asin and acos, it computes sqrt(1-z²). Previously, the subtraction was done using the constant Complex.ONE, so in your case we ended up by computing 0 - 0 for the imaginary part, losing the sign. Now we use directly the the opposite of the imaginary part rather than performing a subtraction from 0. Is seems I forgot to change the javadoc, though.

**Comment by axkr** [comment]
I'm using the `asin` to calculate `inverseHaversine` 

So this case is in my JUnit suite is also involved:

```
InverseHaversine(1.7)
```

See:
- https://www.wolframalpha.com/input/?i=InverseHaversine%28x%29

**Comment by maisonobe** [comment]
I confirm the current result is correct, i.e. the branch cut is properly implemented for asin.

**Comment by axkr** [comment]
From my understanding the **imaginary part** of `asin(x)` must be negative for all `x > 1.0`  and must be positive for  all `x < 1.0` and `x` written with the `Complex.valueOf(x, +/- 0.0).asin()` syntax. See:
- https://www.wolframalpha.com/input/?i=arcsin%28x%29+for+complex+x

I cannot achieve this by writing `Complex.valueOf(arg1, -0.0).asin()` for both conditions. Is there a simpler way or must I add the condition explicitly?

```
    // gives wrong results
    System.out.println(Complex.valueOf(-2.0, -0.0).asin());
    System.out.println(Complex.valueOf(2.0, 0.0).asin());
```

**Comment by maisonobe** [comment]
> From my understanding the **imaginary part** of `asin(x)` must be negative for all `x > 1.0` and must be positive for all `x < -1.0`

No, the function is multi-valued, so some convention must be adopted to select one value only. The classical way is to introduce branch cuts. For asin, there is a branch cut for x > 1 along the real axis (and another one for x < -1). On each side of the cut, the sign of the imaginary part changes. This is more visible on this 3D plot: https://dlmf.nist.gov/4.15.F9.viz, when you select on the right hand side panel the "phase" for the colormap. You will see that at the cut on positive real parts, colors change directly from orange (which correspond to positive imaginary parts) to purple (which correspond to negative imaginary parts). Other inputs for Wolfram Alpha also shows the sign of the imaginary part of asin(x+iy) mathces the sign of y for x > 1. You can for example ollok at https://www.wolframalpha.com/input/?i=asin%282%2Bi%29 versus https://www.wolframalpha.com/input/?i=asin%282-i%29.

What I get with
```
System.out.println(Complex.valueOf(-2.0, -0.0).asin());
    System.out.println(Complex.valueOf(2.0, 0.0).asin());
```

is 
```
(-1.5707963267948966, -1.3169578969248166)
(-1.5707963267948966, 1.3169578969248164)
```
which matches what Wolfram Alpha gives, except that as there is no way to specify minus 0 on Wolfram Alpha, I resort to use 2+1.0e-12i and 2-1.0e-12i.

This also appears here https://dlmf.nist.gov/4.23 and in Abramowitz and Stegun section 4.4.9 (the dlmf is intended to be an updated, extended and modernized version of the legacy Abramowitz and Stegun).

The output for https://www.wolframalpha.com/input/?i=arcsin%28x%29+for+complex+x shows that the interpreter gets lost whith this input string, the first text box reads "Using closest Wolfram|Alpha interpretation: x for complex", so it failed to understand arcsin. I also tried using "asin" instead of "arcsin" in the query, but it failed too.
