### ISSUE TITLE
Snapshot 2.0 -  FieldCopolarC<Complex>#sc() method gives wrong result

### ISSUE THREAD

**Issue by axkr** [Hipparchus-Math/hipparchus#133]
- https://github.com/Hipparchus-Math/hipparchus/blob/a399be2136342f7ba39594e51cd8123cba9de82d/hipparchus-core/src/main/java/org/hipparchus/special/elliptic/FieldJacobiElliptic.java#L84

```
@Test
  public void testComplex() {
    final Complex z = Complex.valueOf(5.2, -2.5);
    final FieldJacobiElliptic<Complex> je = JacobiEllipticBuilder.build(Complex.valueOf(0.3, 1.0)); 
    final FieldCopolarC<Complex> valuesC = je.valuesC(z);

    // should return -0.246094...
    Assert.assertEquals(valuesC.sc().getReal(), 0.22606757155248666, 1.0e-15);
    // should return 0.742022...
    Assert.assertEquals(valuesC.sc().getImaginary(), -0.9241484785898338, 1.0e-15);
  }
```

**Comment by maisonobe** [comment]
It seems that even with a real elliptic parameter, there are problems when the complex argument z is large with respect to the quarter period. I guess this is due to missing reduction of argument.
Anyway, as now we have a more complete implementation of elliptic integrals and theta functions, I will rewrite completely the Jacobi elliptic functions implementations using them (i.e. parameter m → elliptic module k → first complete integrals K and K' → nome q → Jacobi functions θ₁, θ₂, θ₃, and θ₄ → Jacobi elliptic functions).
Just for the fun, here are two plots of sc(z, k=0.8), one with the current implementation and the second one using θ functions. There is obviously something wrong in the first implementation…
![Jacobi-sc-direct-implementation](https://user-images.githubusercontent.com/3736196/123126823-01ee6080-d44a-11eb-9a73-2efc7cce532e.png)
![Jacobi-sc-theta-implementation](https://user-images.githubusercontent.com/3736196/123126844-06b31480-d44a-11eb-9d13-ccf358cb03a0.png)

**Comment by maisonobe** [comment]
I have improved several things in the implementation and pushed the work to master branch.
I have also pushed in the hipparchus-sample module the little program that allowed me to generate the plots above. It simply launches gnuplot and feeds the complex data to it, with several domain coloring method available.

The results are much closer than before, but still not very good (error of about 1.0e-5) on each components.
The same error occurs even if I use high accuracy with Dfp, so I don't know where to check.
Do you have access to yet another high accuracy implementation (i.e. neither Hipparchus nor Wolfram) to check the values?
