### ISSUE TITLE
AkimaSplineInterpolator returns points that are wildly off the graph

### ISSUE THREAD

**Issue by cowwoc** [Hipparchus-Math/hipparchus#172]
My understanding of AkimaSplineInterpolator is that, unlike other interpolators, is not supposed to wiggle very far (or at all) from points on the graph.

However, when I run the following testcase:

```
double[] x = {1616328747, 1616328983, 1616329316, 1616329864, 1616329875};
double[] y = {2.0, 2.0, 2.0, 2.0, 3.0};
UnivariateInterpolator interpolator = new AkimaSplineInterpolator();
UnivariateFunction interpolatorFunction = interpolator.interpolate(x, y);
double value = interpolatorFunction.value(1616329584);
System.out.println("Interpolated value is: " + value + ". Expected: 2.0");
```

I get a value of `-3.9681889999323374` instead of `2.0`. As you can see, none of the `y` values are even negative so, at first glance, this sounds like a pretty clear-cut bug. I don't understand enough about the code or algorithm. Do you have any idea what is going on?

**Comment by cowwoc** [comment]
If you plot the values on a graph, you will see this curve:

![image](https://user-images.githubusercontent.com/633348/140857775-abd5bf44-5486-4763-9e1e-a17c4e43d968.png)

Up to and including `1616329316` the returned values are correct. Then for some reason, the values dip drastically between `1616329316` and `1616329864`. The value returned by `1616329864` and all subsequent values look correct.

I am expecting a gradual increase between points `1616329316` and `1616329864`, with no dip.

**Comment by maisonobe** [comment]
The input data are indeed not polynomial at all since there is a constant first and then a single point with a different value.
Akima splines are cubic polynomials spliced together in such a way the first derivative is continuous at nodes. The derivative itself is computed from functions values only. Such computation is an approximation and does not work well at interval boundaries, so the input data already corresponds to a difficult case.

Looking at the original paper from 1970, the derivatives at internal nodes are computed from differences with a straightforward formula that needs two points on the left and two points on the right of the node. This formula is therefore not applicable to first two points and last two points. The original paper proposes to append two more points using a quadratic interpolation, which reduces interpolation order.

Our implementation is based on the Math.NET Numerics library (which is available under a compatible license). It uses direct interpolation of the derivatives from the first or last three points. I didn't check the formula to see if it is equivalent to Akima's original paper. It uses the same information - three points - and is polynomial, so seem equivalent, but if I compare our results from the results given by the aspline program in a Linux system, we clearly do not get the same results. The aspline program does not exhibit a dip, but a polynomial increase from 2.0 to 3.0, starting at 1616329864 (not 1616329316).

So I have to check further, but think the derivatives at endpoints are a problem, and since the input data is clearly not polynomial at all, the way these derivatives are approximated changes a lot the output.

I'll have to check other implementations to see how they handle this kind of data.

**Comment by cowwoc** [comment]
@maisonobe That is a good catch. I scanned through the Math.NET implementation and I too could not see any obvious differences. But if their code works while ours fails then this is a strong indication that this could be fixed without forcing users to massage the data.

You might want to take a look at https://www.mathworks.com/help/matlab/ref/makima.html#mw_e8ee1c8c-2cc3-46c4-90c4-c3208804ff4e which updates the weights slightly to avoid the endpoint problem and reduce other overshoots that might occur with the original implementation.

https://blogs.mathworks.com/cleve/2019/04/29/makima-piecewise-cubic-interpolation/ provides a more detailed explanation of how this works.

**Comment by maisonobe** [comment]
I have added the modified weight computation yo mentioned, thanks for the suggestion.
It however does not help in the case above because it detects slope changes when there are several points on both sides of the singularity. Here, there is only a single outlier which is the last point of the sample.

**Comment by cowwoc** [comment]
Got it. In my case I ended up reverting to a linear interpolation. In parallel I am investigating why the data shifts so drastically. From my end, I am fine if you close this issue.

**Comment by maisonobe** [comment]
Thanks for your comment.
I will close the issue.
