### ISSUE TITLE
Multivariate Newton method (root finder) implementation available?

### ISSUE THREAD

**Issue by axkr** [Hipparchus-Math/hipparchus#201]
Is there a multivariate Newton method implementation available in hipparchus?

I assume a symbolic implementation will probably be slower than a numerical one?
* https://github.com/axkr/symja_android_library/issues/566

**Comment by maisonobe** [comment]
In the general case, there are no exact roots in multivariate cases.
What is usually done is find a least square solution, i.e. attempt to minimize some cost function that is a sum of squares of residuals rather than attempting to have all residuals exactly equal to zero. If of course there is an exact root, then a least squares solution is also an exact solution.
There are several least squares implementations available in Hipparchus. A general purpose one that works well, even if the start point is far from the solution, is the Levenberg-Marquardt algorithm. A multivariate Newton's method is in fact a Gauss-Newton method (we have that too).

**Comment by axkr** [comment]
> Gauss-Newton method (we have that too).

Do you have any pointer?

**Comment by maisonobe** [comment]
The documentation is available  [here](https://www.hipparchus.org/hipparchus-optim/leastsquares.html)

**Comment by axkr** [comment]
The links to `MultivariateJacobianFunction` and `ConvergenceChecker` in this document don't work?
* https://github.com/Hipparchus-Math/hipparchus/blob/master/hipparchus-optim/src/site/markdown/leastsquares.md

**Comment by axkr** [comment]
> 



> The documentation is available [here](https://www.hipparchus.org/hipparchus-optim/leastsquares.html)

ah ok mI looke at the wrong place
