### ISSUE TITLE
Improve release guide

### ISSUE THREAD

**Issue by BryanCazabonne** [Hipparchus-Math/hipparchus#277]
The release guide could be improved by adding the following information:
- New taks -> Prerequires : (1) Generate a personnal key-ID and (2) Ask for an account on Hipparchus server
- In [Generating signed artifacts](https://github.com/Hipparchus-Math/hipparchus/blob/master/src/site/markdown/release-guide.md#generating-signed-artifacts), say that the whole "hipparchus-aggregator" and "hipparchus-coverage" must be removed by "right clic" and "Delete"
- Add a new section after [Uploading non-maven artifacts](https://github.com/Hipparchus-Math/hipparchus/blob/master/src/site/markdown/release-guide.md#uploading-non-maven-artifacts). The name can be "Prepare the site for the release" and shall contain the operations to perform.
- Improve the "After the vote" section : (1) Create a dedicated section for tagging the version (2) Add a section for merging release-X.Y into master (3) Add a section explaining how releasing on sonatype (4) Add a section "Declare the release on Github" by adding a new release in https://github.com/Hipparchus-Math/hipparchus/releases/ and (5) Add a new section "Finalize the site after the successful vote"

**Comment by axkr** [comment]
Dependabot already creates 3.0 changes. Is this intended?
- https://github.com/axkr/symja_android_library/pull/832

**Comment by maisonobe** [comment]
No, it is not intended and indeed the dependencied reference the 3.0-SNAPSHOT version, not the upcoming final 3.0.

**Comment by maisonobe** [comment]
After a quick look, I think it is due to the repositories list.

For the general public, the version is still only available in the [staging repository](https://oss.sonatype.org/content/repositories/orghipparchus-1042/) and the latest official version in [maven central](https://central.sonatype.com/artifact/org.hipparchus/hipparchus/versions) is still 2.3.

For expert uses, our own [repository](https://packages.orekit.org/#browse/browse:maven-releases:org%2Fhipparchus%2Fhipparchus%2F3.0) that is triggered by the Continuous Integration framework provides all versions, even development ones. When the branch for 3.0 release was created during the release process, the maven artifacts were pushed there automatically.
