### ISSUE TITLE
[Feature Request] Missing implementation

### ISSUE THREAD

**Issue by BryanCazabonne** [Hipparchus-Math/hipparchus#34]
The class _PolynomialFunction_ implements the interface _UnivariateDifferentiableFunction_, it can be interesting if this class implements also the interface _RealFieldUnivariateFunction_
The same remark can be done also with _PolynomialFunctionNewtonForm_ and _PolynomialSplineFunction_
Thanks

**Comment by maisonobe** [comment]
[disclaimer: Bryan is my intern, so I know what the underlying problem is]

Having _PolynomialFunction_ implement  _RealFieldUnivariateFunction_ would indeed not be general
enough as _RealFieldUnivariateFunction_ is a generic interface which imposes to select the field type T at class level. So we would need to have something like:

    public class PolynomialFunction
      implements UnivariateDifferentiableFunction, RealFieldUnivariateFunction<some field>

What we need is to have the generic type T appear at the level of the value() method, not
at the level of the interface/class.

So we need to introduce a new interface, lets call it FieldUnivariateFunction, where the interface
is not generic, but the value method is.

Unfortunately, we can neither say that FieldUnivariateFunction extends RealFieldUnivariateFunction nor the opposite. Both interfaces are independent of each other. What we can do, however, is have
a default method in one interface that convert an instance into the other type by "fixing" the type T.

I'll do it in a few minutes.
