### ISSUE TITLE
Build fails on Java 11

### ISSUE THREAD

**Issue by wardev** [Hipparchus-Math/hipparchus#50]
When running `mvn clean install` on Java 11 it fails when trying to run the tests because `@{jacoco.agent.args}` is not replaced by anything. Applying the following patch seems to fix the build, but I don't know how it will affect other versions of java.

```diff
diff --git a/hipparchus-parent/pom.xml b/hipparchus-parent/pom.xml
index 0c6fec34e..cbcd23a5c 100644
--- a/hipparchus-parent/pom.xml
+++ b/hipparchus-parent/pom.xml
@@ -600,7 +600,7 @@
             <excludes>
               <exclude>**/*AbstractTest.java</exclude>
             </excludes>
-            <argLine>@{jacoco.agent.args} -Xmx1200m</argLine>
+            <argLine>-Xmx1200m</argLine>
             </configuration>
         </plugin>
         <plugin>

```

**Comment by maisonobe** [comment]
This was added so the continuous integration server at https://ci.orekit.org can provide code coverage.
The property should be set automatically by the prepare-agent goal of jacoco maven plugin.

However, I currently cannot see if is works or not because the ci is failing on everything. It is *not* due to the commits in #46 because jenkins also failed with the same error on a manually triggerd build on Orekit. In fact, I cannot run even a simple "mvn package" on the server for now. I guess there is a configuration problem on the server itself.

Could you look at the java 11/ jacoco maven plugin bad interaction while I look at the ci.orekit.org issue?

**Comment by maisonobe** [comment]
The Orekit Continuous Integration server works again, kudos to Sébastien who found this was due
to an OpenJDK8 update (see  https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=911925).

**Comment by maisonobe** [comment]
I was not able to reproduce the failure. I ran "mvn clean install" on a Debian computer with OpenJDK 11.0.1 (build 11.0.1+13-Debian-2) and it completed flawlessly.

**Comment by wardev** [comment]
Maybe it's something specific to my machine. I'll investigate. Also I was building with Java 10 because Ubuntu packages Java 10 as Java 11 for some reason.
