### ISSUE TITLE
DerivativeStructure  for symbolic derivatives

### ISSUE THREAD

**Issue by axkr** [Hipparchus-Math/hipparchus#51]
Can you show an example/outline, how to implement a `DerivativeStructure` based on symbolic derivation?

At the moment I've used my own NewtonSolver in [FindRoot](https://github.com/axkr/symja_android_library/blob/master/symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/reflection/system/FindRoot.java), but it would be nice to have a general solution which I can use with hipparchus.

**Comment by maisonobe** [comment]
In most cases, the idea behind `DerivativeStructure` is to remove the need for symbolic differentiation: user just implement f(x) with x being a `DerivativeStructure` instead of a primitive double, and the derivatives come for free.

If user already has expressions for both f(x) and df(x)/dx (and possibly higher order derivatives), then using `DerivativeStructure` can still be used, but in this case the `DerivativeStructure` will only be used to store the derivatives, not to compute them. Here is one way to build a `DifferentiableUnivariateFunction` from two `UnivariateFunction` implementing f(x) and df(x)/dx in the case symbolic differentiation allowed the user to implement both

```java
  public static void DifferentiableUnivariateFunction toDifferentiableUnivariateFunction(
   final  UnivariateFunction f, final UnivariateFunction fPrime) {
    return new DifferentiableUnivariateFunction {

      public double value(final double x) {
        return f.value(x);
      }

      public DerivativeStructure value(final DerivativeStructure x) {
        return x.getFactory().build(f.value(x),
                                                  fPrime.value(x) * x.getPartialDerivative(1));
      }

    };
  }
```

Beware I wrote this just off the top of my head, you'll have to adjust to suit your needs. This also will
work *only* if the `DerivativeStructure` variable `x` passed as the argument of the second method is a
derivative with one parameter and order one. If the variable is more rich, we should provide more derivatives to the factory `build` method.

Also be aware that Newton method which requires derivatives is in fact less efficient than for example `BracketingNthOrderBrentSolver`. The first method is only order 2 whereas the other method can be alomst any order. The default is to set it to order 5 and it work very well in this configuration, even without derivatives.

Is this what you were looking for?
