### ISSUE TITLE
Improve error message for non-bracketing interval

### ISSUE THREAD

**Issue by wardev** [Hipparchus-Math/hipparchus#56]
Currently we see error messages like "Interval does not bracket a root: f(1.0) = -0.0, f(1.0) = -0.0" which is misleading because the numbers are rounded instead of using their full precision. Since these exception messages are primarily for developers the full precision should be used.

See also: https://forum.orekit.org/t/workaround-to-interval-does-not-bracket-a-root-f-x-0-f-y-0-7/487

**Comment by maisonobe** [comment]
This change makes the Continuous Integration fail in MathRuntimeExceptionTest.testGetMessageError(). See https://ci.orekit.org/job/hipparchus/. Depending on the java version, we either have the overriden toString() method (which intentionally fails) called, and the "toString failed" message is properly retrived. The corresponding stacktrace is this one:

```
	Suppressed: java.lang.RuntimeException: toString failed
		at org.hipparchus.exception.MathRuntimeExceptionTest$1.toString(MathRuntimeExceptionTest.java:30)
		at java.text.MessageFormat.subformat(MessageFormat.java:1280)
		at java.text.MessageFormat.format(MessageFormat.java:865)
		at java.text.Format.format(Format.java:157)
```

Or we have (and this is what happened in the CI run)

```
Suppressed: java.lang.IllegalArgumentException: Cannot format given Object as a Number
		at java.text.DecimalFormat.format(DecimalFormat.java:507)
		at java.text.Format.format(Format.java:157)
		at java.text.MessageFormat.subformat(MessageFormat.java:1322)
		at java.text.MessageFormat.format(MessageFormat.java:865)
		at java.text.Format.format(Format.java:157)
```

In the later case, we don't retrieve the "toString failed" part and the test fails.

We could probably change this test to use another exception rather than NOT_BRACKETING_INTERVAL.

We should also change line 185 of LocalizedCoreFormats_fr.utf8 to read (all on one line):
```
NOT_BRACKETING_INTERVAL =  l''intervalle n''encadre pas une racine : f({0,number,##0.################E0}) = {2,number,##0.################E0}, f({1,number,##0.################E0}) = {3,number,##0.################E0}
```

**Comment by wardev** [comment]
Sorry for breaking the build. I'll fix it.

**Comment by wardev** [comment]
OK, pushed commit should fix it.

It would be nice to find a way to make the exception messages always use the full precision of numbers, but that seems like a bigger issue.

**Comment by wardev** [comment]
closing this because I think I forgot to after pushing that last commit.
