### ISSUE TITLE
Sqrt() with imaginary part == -0.0

### ISSUE THREAD

**Issue by axkr** [Hipparchus-Math/hipparchus#75]
```
new Complex(-0.5708, -0.0).sqrt()
```

returns `(0.0, -0.7555130707009641)` instead of `(0.0, 0.7555130707009641)`

**Comment by axkr** [comment]
Similar problem with `Complex.ZERO.cos()`

```
	@Test
	public void testCosZero() {
		Complex cosX = Complex.ZERO.cos();
		System.out.println(cosX);
		assertEquals(cosX, Complex.ONE);
	}
```

**Comment by maisonobe** [comment]
> Couldn't we simply convert -0.0 values to 0.0 in the Complex constructors?

I'm on the fence on this.
Signed floating point 0 is a general feature from IEEE754 that has been around for decades and is useful in some places. In fact, I would even say it is more important for complex numbers that for real numbers because it allows for example to select the proper value at branch cuts. The sqrt example you give *is* a correct result as the point is exactly on a branch cut (the non-positive real axis). So as you are on a singularity you do experience corner-case behavior and in this case the signed 0 is there to help choosing the side of the cut.

The example for cosine is also correct, as per the definition cos(x + i y) = cos(x) cosh(y) - i sin(x) sinh(y): the minus sign implies that for x = 0 the imaginary part has a signed reversed with respect to y, hence the -0.0 you see. In this second example, there are no consequences as for (1 - 0.0 i) and (1 + 0.0 i) are in the same location in the complex plane.

**Comment by axkr** [comment]
I've only thought about the subsequent calculations which flipped the sign in my (internal) example.
But of course every single result makes sense of if using selecting the proper value at branch cuts.
