### ISSUE TITLE
Error in ComplexEigenDecomposition?

### ISSUE THREAD

**Issue by axkr** [Hipparchus-Math/hipparchus#99]
I would have expected the same result for real and complex eigen values in the example below?

BTW: for debugging a default `toString()` implementation for `FieldVector` and `FieldMatrix` would be nice.

```

import org.hipparchus.complex.Complex;
import org.hipparchus.linear.ComplexEigenDecomposition;
import org.hipparchus.linear.EigenDecomposition;
import org.hipparchus.linear.FieldVector;
import org.hipparchus.linear.MatrixUtils;
import org.hipparchus.linear.RealMatrix;
import org.hipparchus.linear.RealVector;

public class ComplexEigenExample {
	private static final RealMatrix A = MatrixUtils.createRealMatrix(new double[][] { //
			{ 1.0, 0.0, 0.0 }, //
			{ 0.0, 1.0, 0.0 }, //
			{ 0.0, 0.0, 1.0 } });

	public static void main(String[] args) {
		EigenDecomposition ed = new EigenDecomposition(A);
		RealVector ev = ed.getEigenvector(0);
		System.out.println(ev); 
		ev = ed.getEigenvector(1);
		System.out.println(ev);   
		ev = ed.getEigenvector(2);
		System.out.println(ev);  
		System.out.println(); 
		System.out.println();

		ComplexEigenDecomposition eigenDecomp = new ComplexEigenDecomposition(A);
		FieldVector<Complex> cv = eigenDecomp.getEigenvector(0);
		for (int i = 0; i < cv.getDimension(); i++) {
			System.out.print(cv.getEntry(i).toString() + ";");
		}
		System.out.println();
		cv = eigenDecomp.getEigenvector(1);
		for (int i = 0; i < cv.getDimension(); i++) {
			System.out.print(cv.getEntry(i).toString() + ";");
		}
		System.out.println();
		cv = eigenDecomp.getEigenvector(2);
		for (int i = 0; i < cv.getDimension(); i++) {
			System.out.print(cv.getEntry(i).toString() + ";");
		}
		System.out.println();
	}
}
```

**Comment by maisonobe** [comment]
This is definitely a bug.
The method implemented for Complex eigen decomposition is different than the one for real decomposition.
The complex version uses inverse iteration to compute eigenvectors ones eigenvalues are known, whereas
real decomposition uses the Q matrix from Householder decomposition.
The complex version does not work when several eigenvalues are the same (here they are all equal to 1),
and the loop over eigenvalues generates the same vector three times since the eigenvalues are equal.

This is really a serious bug caused by a big design error.

**Comment by axkr** [comment]
There are still differences in the result of real and complex eigen vectors.

```
package org.matheclipse.core.examples;

import org.hipparchus.complex.Complex;
import org.hipparchus.linear.ComplexEigenDecomposition;
import org.hipparchus.linear.EigenDecomposition;
import org.hipparchus.linear.FieldVector;
import org.hipparchus.linear.MatrixUtils;
import org.hipparchus.linear.RealMatrix;
import org.hipparchus.linear.RealVector;

public class ComplexEigenExample2 {
  private static final RealMatrix A =
      MatrixUtils.createRealMatrix(
          new double[][] { //
            {1.0, 2.0, 3.0}, //
            {4.0, 5.0, 6.0}, //
            {7.0, 8.0, 9.0}
          });

  public static void main(String[] args) {
    System.out.println("Real example");
    mainReal();
    System.out.println("----------------------------------------------------------------");
    System.out.println("Complex example");
    mainComplex();
  }

  private static void mainReal() {
    EigenDecomposition eigenDecomp = new EigenDecomposition(A);
    RealVector cv = eigenDecomp.getEigenvector(0);
    for (int i = 0; i < cv.getDimension(); i++) {
      System.out.print(cv.getEntry(i) + ";");
    }
    System.out.println();
    cv = eigenDecomp.getEigenvector(1);
    for (int i = 0; i < cv.getDimension(); i++) {
      System.out.print(cv.getEntry(i) + ";");
    }
    System.out.println();
    cv = eigenDecomp.getEigenvector(2);
    for (int i = 0; i < cv.getDimension(); i++) {
      System.out.print(cv.getEntry(i) + ";");
    }
    System.out.println();
  }

  private static void mainComplex() {
    ComplexEigenDecomposition eigenDecomp = new ComplexEigenDecomposition(A);
    FieldVector<Complex> cv = eigenDecomp.getEigenvector(0);
    for (int i = 0; i < cv.getDimension(); i++) {
      System.out.print(cv.getEntry(i).toString() + ";");
    }
    System.out.println();
    cv = eigenDecomp.getEigenvector(1);
    for (int i = 0; i < cv.getDimension(); i++) {
      System.out.print(cv.getEntry(i).toString() + ";");
    }
    System.out.println();
    cv = eigenDecomp.getEigenvector(2);
    for (int i = 0; i < cv.getDimension(); i++) {
      System.out.print(cv.getEntry(i).toString() + ";");
    }
    System.out.println();
  }
}
```

**Comment by maisonobe** [comment]
The differences are normal, for a given eigenvector v, any scaled vector k * v is also an eigenvector, so they may look different

In the case above, the eigenvalues are all real and in decreasing magnitude order are 16.116843969807043, -1.1168439698070438 and 0 (both algorithms find -9.296497310143093E-16). Bothn algorithms find the eigenvalues in the same order. For real version, the order is enforced to be decreasing magnitude, but I am not sure it is the same for complex version, anyway in this case they both find the same values.

Normalization and even sign of the eigenvectors however are different, so the vector appear different despite the represent the same vector space. For example multiplying the first vector from real decomposition by  1.2214881766496868461 gives the first vector of the complex decomposition. The scaling factor is 1.2240438381866837498 for the second vector and -1.2247448713915893982 for the third vector.

As in this case all eigenvalues are different, there is a single scaling factor since the sub-vector space is dimension 1 for each eigenvalue. If one eigenvalue were repeated, then it would correspond to several eigenvectors and in this case both decompositions could lead to very different (but still correct) eigenvectors that correspond to linear combinations : i.e. they would generate the same sub-vector space.

**Comment by axkr** [comment]
So the algorithms use a different approach to get to the result. I assumed they should be very similar.
